/** Studio PATCH fields that get field-level audit rows. */
export const AUDIT_BOOKING_FIELDS = [
  "title",
  "hotel_name",
  "city",
  "country",
  "chain",
  "start_date",
  "end_date",
  "nights",
  "num_rooms",
  "num_adults",
  "num_children",
  "supplier_name",
  "supplier_ref",
  "booking_channel",
  "currency",
  "cost_amount",
  "sell_amount",
  "commission_expected",
  "status",
  "confirmed_at",
  "cancelled_at",
  "cancellation_reason",
  "cancellation_deadline",
  "cancellation_policy",
  "ticket_time_limit",
  "internal_notes",
  "vip_flag",
  "service_details",
] as const;
