/** Studio PATCH fields that get field-level audit rows. */
export const AUDIT_CLIENT_FIELDS = [
  "display_name",
  "title",
  "first_name",
  "last_name",
  "legal_name",
  "email",
  "phone",
  "whatsapp",
  "preferred_contact_method",
  "preferred_language",
  "timezone",
  "nationality",
  "city_of_residence",
  "company",
  "address_line_1",
  "address_line_2",
  "address_city",
  "address_state",
  "address_postal_code",
  "address_country",
  "relationship_owner_id",
  "tier_id",
  "client_since",
  "referred_by_client_id",
  "important_dates",
  "guest_notes",
  "internal_notes",
  "avatar_url",
] as const;
