export { createServiceClient, getServiceClient } from "./client";
export { dbConfigError, dbQueryError } from "./errors";
export {
  acceptInviteAndCreateMember,
  createStudioInvite,
  approveClientRecord,
  deactivateClient,
  computeContractedStayCost,
  findActiveDestinationProfileById,
  findActivePropertyById,
  findActivePropertyWithSupplierCodes,
  findActiveRoutingOverride,
  findActiveStudioRoleBySlug,
  findClientById,
  findDestinationProfileByText,
  findClientDisplayNamesByIds,
  findClientIdsByDisplayName,
  findClientDocumentById,
  findClientFamily,
  findClientHealth,
  findClientPreferenceById,
  findClientRelationshipById,
  findPendingInviteByEmail,
  findSimilarClients,
  findTeamMemberByEmail,
  findTeamMemberById,
  findTripById,
  findTripLegById,
  findTripLineItemById,
  getClientProfileSignals,
  getKnowledgeBaseSetting,
  getRateSourcesSetting,
  isRateSourceEnabled,
  mergeKnowledgeBaseSetting,
  mergeRateSourcesSetting,
  refreshClientProfileCompletenessRpc,
  clearFamilyPrimary,
  countFamilyMembers,
  deleteClientDocument,
  deleteClientRelationship,
  deleteFamily,
  deleteFamilyMember,
  insertClient,
  insertClientAuditLogs,
  insertClientDocument,
  insertClientPreference,
  insertClientRelationship,
  insertFamily,
  insertFamilyMember,
  insertTripLineItem,
  listActiveContractOffersForStay,
  listActiveContractedRatesForStay,
  listActiveDestinationProfiles,
  listActiveDestinationTypeDefaults,
  listActiveNegotiatedRateCodes,
  listActivePeakWindowsForStay,
  listActivePropertyContractsForProperty,
  listActiveRateAddonsForStay,
  listActiveStudioPermissions,
  listActiveStudioRoles,
  listActiveSupplierCodesForProperty,
  listActiveWholesalersForProfile,
  stayNightCount,
  listClientAuditLogs,
  listClientDirectoryFilterValues,
  listClientDocuments,
  listClientGuests,
  listClientMergeCandidates,
  listClientPreferences,
  listClientRelationships,
  findBookingById,
  findSuccessorBookingId,
  findTeamMemberNamesByIds,
  insertBooking,
  insertBookingAuditLogs,
  deleteBookingTraveller,
  findBookingTravellerById,
  insertBookingTraveller,
  updateBookingTraveller,
  listBookingAuditLogs,
  listBookingTravellers,
  listBookings,
  updateBooking,
  listClients,
  listPendingInvites,
  listPermissionSlugsByRole,
  listStudioRolePermissionGrants,
  listTeamMembers,
  parseRateSourcesSetting,
  replaceRolePermissions,
  revokeStudioInvite,
  searchClients,
  searchFamilies,
  touchStudioInvite,
  touchTeamMemberLastLogin,
  updateClient,
  updateClientDocument,
  updateClientPreference,
  updateFamilyMember,
  updateFamilyName,
  updateMemberProfile,
  updateTeamMember,
  upsertClientHealth,
  upsertKnowledgeBaseSetting,
  upsertRateSourcesSetting,
  updateTripLineItemStatus,
  compareKbEntitiesForResolve,
  countActiveKbEntitiesByTypeForCity,
  deactivateKbEntities,
  deleteTripLineItemsByIds,
  applyKbResolveCandidatesForLeg,
  findActiveKbCityByCountryAndName,
  findActiveKbCityById,
  findActiveKbCountryByCode,
  findActiveKbCountryById,
  findActiveKbDestinationAudienceNote,
  findActiveKbEntityByExternalId,
  findActiveKbEntityById,
  findActiveKbEntityByIdentity,
  findActiveKbEntityByPropertyId,
  findActiveKbRegionById,
  findActiveKbVisaRule,
  findKbActivityDetails,
  findKbCountryFacts,
  findKbDestinationFacts,
  findKbEntityById,
  findKbHotelDetails,
  findKbItineraryById,
  findKbRestaurantDetails,
  findKbScrapeJobById,
  findKbScrapeJobBySourceId,
  findKbSourceById,
  findKbVendorDetails,
  findPreferredKbItineraryForCountry,
  finishKbScrapeRun,
  insertKbCustomerFeedback,
  insertKbDraftCandidatesForLeg,
  insertKbEntity,
  insertKbInternalNote,
  insertKbScrapeRun,
  insertKbSource,
  listActiveKbCitiesForCountry,
  listActiveKbCountries,
  listActiveKbEntities,
  listActiveKbHotelRoomCategories,
  listActiveKbRegions,
  listApprovedKbFactsForEntity,
  listExpiredLlmGeneralKbEntities,
  listKbCustomerFeedbackForEntity,
  listKbFactChunksForFact,
  listKbHotelCandidatesForCity,
  listKbHotelConsortia,
  listKbInternalNotesForEntity,
  listKbItineraries,
  listKbItineraryItems,
  listKbScrapeJobs,
  listKbScrapeRunsForJob,
  listKbSources,
  listReplaceableKbDraftLineItems,
  loadKbCityPlaceBundle,
  loadKbCountryPlaceBundle,
  loadKbEntityDetailBundle,
  loadKbHotelDetailBundle,
  loadKbItineraryBundle,
  markKbFeedbackUsedInAdvisorTake,
  replaceKbDraftCandidatesForLeg,
  searchApprovedKbFacts,
  searchKbContent,
  updateKbEntity,
  updateKbScrapeJobAfterRun,
  updateKbSource,
  updateTripLegKbSelectionStatus,
  upsertKbScrapeJob,
  upsertKbVisaRule,
  verifyKbEntity,
  findClientTierById,
  findClientTierBySlug,
  findDefaultClientTier,
  listActiveClientTiers,
  type BookingDirectoryRow,
  type ClientDirectoryFilterValues,
  type ClientDirectoryRow,
  type ComputeContractedStayCostInput,
  type FindContractedRateInput,
  type InsertKbCustomerFeedbackInput,
  type InsertKbDraftCandidateInput,
  type InsertKbEntityInput,
  type InsertKbInternalNoteInput,
  type InsertKbScrapeRunInput,
  type InsertKbSourceInput,
  type KbCityPlaceBundle,
  type KbCountryPlaceBundle,
  type KbEntityDetailBundle,
  type KbHotelDetailBundle,
  type KbItineraryBundle,
  type ListBookingsResult,
  type ListKbEntitiesInput,
  type ListKbItinerariesInput,
  type ListContractRowsForStayInput,
  type ListPeakWindowsInput,
  type PropertyWithSupplierCodes,
  type SearchKbContentInput,
  type SearchKbContentResult,
  type SearchKbFactsInput,
  type UpdateBookingRecord,
  type UpdateKbEntityInput,
  type UpdateKbSourceInput,
  type UpsertKbScrapeJobInput,
  type UpsertKbVisaRuleInput,
  type ClientFilterOwnerOption,
  type FamilySearchHit,
  type InsertClientInput,
  type InsertClientDocumentInput,
  type InsertClientPreferenceInput,
  type InsertClientRelationshipInput,
  type InsertFamilyMemberInput,
  type InsertTripLineItemInput,
  type KnowledgeBaseSettingPatch,
  type ListClientsResult,
  type UpdateClientDocumentRecord,
  type UpdateClientPreferenceRecord,
  type UpdateClientRecord,
} from "./queries";
export {
  buildClientDocumentPath,
  CLIENT_DOCUMENTS_BUCKET,
  createClientDocumentDownloadUrl,
  createClientDocumentUploadUrl,
  removeClientDocumentFile,
  type SignedUpload,
} from "./storage";
export {
  DEFAULT_STUDIO_ROLE_SLUGS,
  type Booking,
  type BookingAuditLog,
  type BookingAuditPerformedBy,
  type BookingServiceType,
  type BookingSource,
  type BookingStatus,
  type BookingTraveller,
  type BookingTravellerGender,
  type BookingTravellerRole,
  type Client,
  type ClientAuditAction,
  type ClientAuditLog,
  type ClientDocument,
  type ClientHealthProfile,
  type ClientImportantDate,
  type ClientMergeCandidate,
  type ClientPreference,
  type ClientRelationship,
  type ClientReviewStatus,
  type ClientSource,
  type ClientTier,
  type ClientTierSummary,
  type CompanySetting,
  type DefaultStudioRoleSlug,
  type DestinationProfile,
  type DestinationRoutingOverride,
  type DestinationRoutingPattern,
  type DestinationType,
  type DestinationTypeDefault,
  type DestinationWholesaler,
  type FamilyMemberRole,
  type FamilyMembership,
  type GuestUser,
  type InviteStatus,
  type KbActivityDetails,
  type KbCity,
  type KbContractStatus,
  type KbCountry,
  type KbCountryFacts,
  type KbCountryVisaRule,
  type KbCustomerFeedback,
  type KbDestinationAudienceNote,
  type KbDestinationFacts,
  type KbEntity,
  type KbEntityType,
  type KbFact,
  type KbFactChunk,
  type KbFactStatus,
  type KbHotelConsortia,
  type KbHotelDetails,
  type KbHotelRoomCategory,
  type KbInternalNote,
  type KbItinerary,
  type KbItineraryItem,
  type KbProvenance,
  type KbRegion,
  type KbRestaurantDetails,
  type KbScrapeJob,
  type KbScrapeRun,
  type KbScrapeRunStatus,
  type KbSelectionStatus,
  type KbSource,
  type KbSourceType,
  type KbTier,
  type KbTripStyle,
  type KbVendorDetails,
  type KbVendorType,
  type KbVisaEntryType,
  type KnowledgeBaseSetting,
  type Layer2Pattern,
  type NegotiatedRateCode,
  type PreferredContactMethod,
  type Property,
  type PropertyContract,
  type PropertyContractBenefit,
  type PropertyContractedRate,
  type PropertyContractOffer,
  type PropertyContractOfferType,
  type PropertyContractPayout,
  type PropertyContractPolicies,
  type PropertyContractType,
  type PropertyRateAddon,
  type PropertyRateAddonType,
  type PropertyRateAddonUnit,
  type PropertyRateBasis,
  type PropertyRateSeasonCode,
  type PropertySupplierCode,
  type RatePeakWindow,
  type RateSearchEvent,
  type RateSourceChannelFlag,
  type RateSourceCode,
  type RateSourcesSetting,
  type SimilarClientMatch,
  type StudioInvite,
  type StudioPermissionRecord,
  type StudioRole,
  type StudioRolePermissionRecord,
  type StudioRoleRecord,
  type TeamMember,
  type Trip,
  type TripAttachment,
  type TripAttachmentPurpose,
  type TripAttentionSnooze,
  type TripChatChannel,
  type TripChatMessage,
  type TripChatMode,
  type TripChatRole,
  type TripClient,
  type TripClientRole,
  type TripClientVisibility,
  type TripDocument,
  type TripDocumentStatus,
  type TripDocumentType,
  type TripIdempotencyKey,
  type TripItineraryDay,
  type TripItineraryDaySource,
  type TripLeg,
  type TripLegItineraryStatus,
  type TripLineItem,
  type TripLineItemAvailabilityStatus,
  type TripLineItemCategory,
  type TripLineItemSource,
  type TripLineItemStatus,
  type TripLineItemUnit,
  type TripPendingConfirm,
  type TripPendingConfirmStatus,
  type TripSource,
  type TripStatus,
  type TripUndoAction,
} from "./schema";
export {
  getSupabaseEnv,
  supabaseEnvSchema,
  type SupabaseEnv,
} from "./validation";
