export { createServiceClient, getServiceClient } from "./client";
export { dbConfigError, dbQueryError } from "./errors";
export {
  acceptInviteAndCreateMember,
  createStudioInvite,
  approveClientRecord,
  deactivateClient,
  findActiveStudioRoleBySlug,
  findClientById,
  findClientDisplayNamesByIds,
  findClientIdsByDisplayName,
  findClientDocumentById,
  findClientFamily,
  findClientHealth,
  findClientPreferenceById,
  findClientRelationshipById,
  findPendingInviteByEmail,
  findSimilarClients,
  findTeamMemberByEmail,
  findTeamMemberById,
  getClientProfileSignals,
  refreshClientProfileCompletenessRpc,
  clearFamilyPrimary,
  countFamilyMembers,
  deleteClientDocument,
  deleteClientRelationship,
  deleteFamily,
  deleteFamilyMember,
  insertClient,
  insertClientAuditLogs,
  insertClientDocument,
  insertClientPreference,
  insertClientRelationship,
  insertFamily,
  insertFamilyMember,
  listActiveStudioPermissions,
  listActiveStudioRoles,
  listClientAuditLogs,
  listClientDirectoryFilterValues,
  listClientDocuments,
  listClientGuests,
  listClientMergeCandidates,
  listClientPreferences,
  listClientRelationships,
  findBookingById,
  findSuccessorBookingId,
  findTeamMemberNamesByIds,
  insertBooking,
  insertBookingAuditLogs,
  deleteBookingTraveller,
  findBookingTravellerById,
  insertBookingTraveller,
  updateBookingTraveller,
  listBookingAuditLogs,
  listBookingTravellers,
  listBookings,
  updateBooking,
  listClients,
  listPendingInvites,
  listPermissionSlugsByRole,
  listStudioRolePermissionGrants,
  listTeamMembers,
  replaceRolePermissions,
  revokeStudioInvite,
  searchClients,
  searchFamilies,
  touchStudioInvite,
  touchTeamMemberLastLogin,
  updateClient,
  updateClientDocument,
  updateClientPreference,
  updateFamilyMember,
  updateFamilyName,
  updateMemberProfile,
  updateTeamMember,
  upsertClientHealth,
  findClientTierById,
  findClientTierBySlug,
  findDefaultClientTier,
  listActiveClientTiers,
  type BookingDirectoryRow,
  type ClientDirectoryFilterValues,
  type ClientDirectoryRow,
  type ListBookingsResult,
  type UpdateBookingRecord,
  type ClientFilterOwnerOption,
  type FamilySearchHit,
  type InsertClientInput,
  type InsertClientDocumentInput,
  type InsertClientPreferenceInput,
  type InsertClientRelationshipInput,
  type InsertFamilyMemberInput,
  type ListClientsResult,
  type UpdateClientDocumentRecord,
  type UpdateClientPreferenceRecord,
  type UpdateClientRecord,
} from "./queries";
export {
  buildClientDocumentPath,
  CLIENT_DOCUMENTS_BUCKET,
  createClientDocumentDownloadUrl,
  createClientDocumentUploadUrl,
  removeClientDocumentFile,
  type SignedUpload,
} from "./storage";
export {
  DEFAULT_STUDIO_ROLE_SLUGS,
  type Booking,
  type BookingAuditLog,
  type BookingAuditPerformedBy,
  type BookingServiceType,
  type BookingSource,
  type BookingStatus,
  type BookingTraveller,
  type BookingTravellerGender,
  type BookingTravellerRole,
  type Client,
  type ClientAuditAction,
  type ClientAuditLog,
  type ClientDocument,
  type ClientHealthProfile,
  type ClientImportantDate,
  type ClientMergeCandidate,
  type ClientPreference,
  type ClientRelationship,
  type ClientReviewStatus,
  type ClientSource,
  type ClientTier,
  type ClientTierSummary,
  type CompanySetting,
  type DefaultStudioRoleSlug,
  type DestinationProfile,
  type DestinationRoutingOverride,
  type DestinationRoutingPattern,
  type DestinationType,
  type DestinationTypeDefault,
  type DestinationWholesaler,
  type FamilyMemberRole,
  type FamilyMembership,
  type GuestUser,
  type InviteStatus,
  type KbEntity,
  type KbEntityType,
  type KbFact,
  type KbFactChunk,
  type KbFactStatus,
  type KbProvenance,
  type KbSource,
  type KnowledgeBaseSetting,
  type Layer2Pattern,
  type NegotiatedRateCode,
  type PreferredContactMethod,
  type Property,
  type PropertyContractedRate,
  type PropertySupplierCode,
  type RatePeakWindow,
  type RateSearchEvent,
  type RateSourceChannelFlag,
  type RateSourceCode,
  type RateSourcesSetting,
  type SimilarClientMatch,
  type StudioInvite,
  type StudioPermissionRecord,
  type StudioRole,
  type StudioRolePermissionRecord,
  type StudioRoleRecord,
  type TeamMember,
  type Trip,
  type TripChatChannel,
  type TripChatMessage,
  type TripChatMode,
  type TripChatRole,
  type TripClient,
  type TripClientRole,
  type TripClientVisibility,
  type TripDocument,
  type TripDocumentStatus,
  type TripDocumentType,
  type TripItineraryDay,
  type TripItineraryDaySource,
  type TripLeg,
  type TripLegItineraryStatus,
  type TripLineItem,
  type TripLineItemCategory,
  type TripLineItemSource,
  type TripLineItemStatus,
  type TripLineItemUnit,
  type TripSource,
  type TripStatus,
} from "./schema";
export {
  getSupabaseEnv,
  supabaseEnvSchema,
  type SupabaseEnv,
} from "./validation";
